version: '3.8'

services:
  postgres:
    image: postgres:15

    container_name: postgres-db

    restart: always

    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: devopsdb

    ports:
      - "5432:5432"